### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by schriftgestalt** [mekkablue/ShowTopsAndBottoms#14]
I got this from a user:
```

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 1411, in raiseException_

  File "GlyphsApp/GlyphsApp/plugins.py", line 1227, in drawBackgroundForLayer_options_

  File "plugin.py", line 279, in background
    self.drawTopsAndBottoms( layer, NSColor.darkGrayColor() )

  File "plugin.py", line 211, in drawTopsAndBottoms
    if bbox.size.height > 0.0:
       ^^^^^^^^^

AttributeError: 'objc.native_selector' object has no attribute 'size'

App:3.3-3301 Plugin:2.0.10-31 System:13.6.6 
```

**Comment by mekkablue** [comment]
Cannot reproduce with build 3303. Can the user?
