### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/ShowTopsAndBottoms#4]
Hi! I get the following error.

Best regards.

```
Traceback (most recent call last):
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/__boot__.py", line 47, in <module>
    _run('ShowTopsAndBottoms.py')
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/__boot__.py", line 45, in _run
    execfile(path, globals(), globals())
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/ShowTopsAndBottoms.py", line 9, in <module>
    class ShowTopsAndBottoms(ReporterPlugin):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector drawForeground of ShowTopsAndBottoms at 0x10b1567b0>
```

**Comment by mekkablue** [comment]
I cannot reproduce this. Which version of Glyphs are you running?
Also, the error message seems to be incomplete. What comes after the word "for"?

**Comment by guidoferreyra** [comment]
2.2.2 and osx El Capitan

**Comment by mekkablue** [comment]
I cannot reproduce it in Version 2.2.2 (826) on El Capitan 10.11.2 (15C50). Does the latest version work for you?

**Comment by guidoferreyra** [comment]
I downloaded again but is not working. Here the complete error message, sorry.

```
Traceback (most recent call last):
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/__boot__.py", line 47, in <module>
    _run('ShowTopsAndBottoms.py')
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/__boot__.py", line 45, in _run
    execfile(path, globals(), globals())
  File "/Users/Guido/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/ShowTopsAndBottoms.py", line 9, in <module>
    class ShowTopsAndBottoms(ReporterPluginSTAB):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector drawBackground of ShowTopsAndBottoms at 0x117959750>
```

**Comment by guidoferreyra** [comment]
I've tried on my other computer a macbook, same result. Both on El Capitan and latest version of Glyph.

**Comment by mekkablue** [comment]
Can you delete your objectsGS.py file in your Scripts folder, and restart Glyphs?

**Comment by guidoferreyra** [comment]
I deleted objectsGS.py but same result, also I tried deleting objectsGS.pyc but nothing again.

**Comment by mekkablue** [comment]
Seems to be the same as https://github.com/mekkablue/ShowItalic/issues/1 which is solved.
