### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vitoriaseven** [mekkablue/ShowTopsAndBottoms#9]
Hi, plugin installs correctly, however, doesn't show in the "View" menu.
I have the latest version 2.5.1 (1141).
Thanks!

**Comment by mekkablue** [comment]
Uninstall and reinstall again, please, I uploaded a new version last night.
If the problem persists, there must be an error message in the Macro Window after startup. Please post it here.

**Comment by vitoriaseven** [comment]
It still doesn't work. This is what's in the macro panel:

`Traceback (most recent call last):
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/plugin.py", line 18, in <module>
    class ShowTopsAndBottoms(ReporterPlugin):
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/plugin.py", line 19, in ShowTopsAndBottoms
    shoulderSet = list(GSGlyphsInfo.indicScripts()) + ["arabic", "hebrew", "thai", "lao", "tibet", "myanmar"]
TypeError: Missing argument: self
`

**Comment by mekkablue** [comment]
I cannot reproduce it, so I can only guess. Try the version I just uploaded, please.
And happy birthday, btw. :)

**Comment by vitoriaseven** [comment]
Thanks! I will give it a try and let you know. 
Thank you so much! :)

**Comment by vitoriaseven** [comment]
Sorry, it's still not working. Removed all the plugins and installed just "Show Tops and Bottoms" but it didn't help. The error in the macro panel is still the same.

**Comment by mekkablue** [comment]
Can you post the error in the macro panel again here. It cannot be the same if you have the latest version because I changed the code in the affected line.

**Comment by vitoriaseven** [comment]
Sure! Here it is:

`Traceback (most recent call last):
  File "/Users/marianeves/Library/Application Support/Glyphs/Repositories/Show Tops and Bottoms/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File "/Users/marianeves/Library/Application Support/Glyphs/Repositories/Show Tops and Bottoms/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File "/Users/marianeves/Library/Application Support/Glyphs/Repositories/Show Tops and Bottoms/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/plugin.py", line 17, in <module>
    shoulderSet = ["arabic", "hebrew", "thai", "lao", "tibet", "myanmar"].__add__( list(GSGlyphsInfo.indicScripts()) )
TypeError: Missing argument: self
`

**Comment by iqblfrds** [comment]
hi, i also just updated the latest version. but that actually makes "show tops and bottom" not appear.

**Comment by mekkablue** [comment]
> but that actually makes "show tops and bottom" not appear

Please verify you only have on Tops and Bottoms in the _Plugins_ folder. And which error message do you get in the Macro Window?

**Comment by mekkablue** [comment]
Please everyone try the version 1.2.4 (16) I just uploaded.

**Comment by vitoriaseven** [comment]
Thank you for the update! It's still not working. This is what I get in the macro panel:

`Traceback (most recent call last):
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File "/Users/marianeves/Library/Application Support/Glyphs/Plugins/ShowTopsAndBottoms.glyphsReporter/Contents/Resources/plugin.py", line 18, in <module>
    shoulderDefaults = list( GSGlyphsInfo.indicScripts() )
TypeError: Missing argument: self
`

**Comment by mekkablue** [comment]
I cannot reproduce this. What happens when you put the following line into _Window > Macro Panel_ and press _Run?_

```python
l = GSGlyphsInfo.indicScripts()
print "l1:", l
l = list(l)
print "l2:", l
```

Can you post the result here?

**Comment by vitoriaseven** [comment]
Sure! Here it is:

`Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Missing argument: self`

**Comment by mekkablue** [comment]
Which macOS are you using?

**Comment by vitoriaseven** [comment]
macOS Sierra v10.12.6

**Comment by mekkablue** [comment]
Did you install modules in Preferences?

**Comment by vitoriaseven** [comment]
I hadn't but I installed them after you asked. I get the same error.

**Comment by mekkablue** [comment]
I think I need access to your machine to see what is really happening. I will hardcode the list in the plugin for now.

**Comment by mekkablue** [comment]
OK, please try the version I just uploaded.

**Comment by vitoriaseven** [comment]
It finally works!!! Thank you so much :)
